src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Auth_URL__c</fullName>
        <label>Auth URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RESTAuthConnection.cls
@RestResource(urlMapping='/AuthConnection/*')
global with sharing class RESTAuthConnection {

@HttpPost   
  global static void doPost(String connectionId, String authorizeUrl) { 
      Connection__c connection = ([SELECT COUNT() FROM connection__c] > 0) ? [SELECT auth_url__c FROM connection__c LIMIT 1] : new connection__c();     
      connection.auth_url__c = authorizeUrl;
      upsert connection;
  }
  
  public static String cName() {
      return 'RESTAuthConnection';
  }
  
  public static String mName() {
      return 'doPost';
  }
}