src/objects/Connection__c.object
<CustomObject>
    <fields>
        <fullName>Auth_URL__c</fullName>
        <label>Auth URL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AuthController.cls
public with sharing class AuthController {
    private Connection__c connection;
    public String authUrl;
    
    public AuthController(){
        Connection__c[] connections = [SELECT auth_url__c FROM connection__c limit 1];
        connection = (connections.size() > 0) ? connections[0] : null;
        if (connection != null) authUrl = connection.auth_url__c;
    }

    public String getAuthUrl() {
        if((connection == null)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL, 'Insufficient Access.'));
            return '';
        } else {
            return authUrl;
        }
    }
}