src/objects/Connection__c.object
<CustomObject>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Heroku_Config__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>App_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The name of the supporting Heroku application.</description>
        <inlineHelpText>The name of the supporting Heroku application. If you did not designate this when you first created the app (i.e. heroku create...), Heroku automatically generated one for you.</inlineHelpText>
        <label>App Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Heroku Config</label>
</CustomObject>

src/classes/HerokuConnectSetup.cls
global without sharing class HerokuConnectSetup implements System.InstallHandler {
    global void onInstall(InstallContext context) {
      if(context.isUpgrade()){
        return;
      }
      
      Connection__c conn = new Connection__c();
      insert conn;
      
      sendRequest(context.installerId());
    }
    
    public static void testRequest() {
      Connection__c conn = new Connection__c();
      insert conn;
      
      String id = UserInfo.getUserId(); 
          
      sendRequest(id);
    }
    
    @future (callout=true)
    public static void sendRequest(String installerId) {
      HttpRequest request = new HttpRequest();
      HttpResponse response = new HttpResponse();
      Http http = new Http();

      User[] users = [SELECT email FROM User WHERE id = :installerId];
      User admin = (users.size() > 0) ? users[0] : null;
      
      Heroku_Config__c heroku_config = Heroku_Config__c.getInstance('Rails App');

      String endpoint = 'https://' + heroku_config.app_name__c  + '.herokuapp.com/organizations';

      request.setMethod('POST');
      request.setEndpoint(endpoint);
      request.setHeader('Content-Type', 'application/json');
      request.setHeader('Accept', 'application/json');
      request.setBody('{"org_id":"'+UserInfo.getOrganizationId()+ '", "admin_email":"' +admin.email+ '", "org_name":"' +UserInfo.getOrganizationName()+ '"}');

      response = http.send(request);
      System.debug(response.toString());
      System.debug(response.getBody());
      System.debug(response.getStatus());
    }
}